### ISSUE TITLE
Token tracking

### ISSUE THREAD

**Issue by Brushstroke90** [paulkim26/collab-worldtour1#97]
Assign tokens to one strand on the door each. 

-name them each ie "Germany 1" and make them a button without action
-Brush requests at least every other strand has the token's side with the logo face outward, if not all :)

**Comment by Brushstroke90** [comment]
Thailand: #1-4
Hub: #5-8
Greece: #9-12
Italy: 13-16
Germany: 17-20

**Comment by Brushstroke90** [comment]
or the scripting way suggested

**Comment by paulkim26** [comment]
My plan as I understand is:
- [ ] Assign tokens to a strand by area
- [ ] Add a message upon revisiting about how many tokens are left there

Personally, I think it would look better as it is now with the tokens are all facing the same side on the door.

**Comment by Brushstroke90** [comment]
aww I just like how he put the logo on them

**Comment by paulkim26** [comment]
I'll see, I was thinking of flipping them all over

**Comment by Brushstroke90** [comment]
that works too :)

**Comment by mrogx** [comment]
If this is what is decided (Add a message upon revisiting about how many tokens are left there), it can be done.
I'll need to write a completely new tokens script for that and also make some changes to each module's logic.

**Comment by paulkim26** [comment]
Sounds good, I'll leave it to you to implement this solution. If you need help understanding my recent modifications to the token Lua script lmk

**Comment by mrogx** [comment]
> Sounds good, I'll leave it to you to implement this solution. If you need help understanding my recent modifications to the token Lua script lmk

All I see is two instances of ` api.setLockValue`. This I miss something else?

**Comment by mrogx** [comment]
done

**Comment by paulkim26** [comment]
> > Sounds good, I'll leave it to you to implement this solution. If you need help understanding my recent modifications to the token Lua script lmk
> 
> All I see is two instances of `api.setLockValue`. Did I miss something else?

Yep that's it

**Comment by paulkim26** [comment]
Sounds good, no preference in the order of the strands.

**Comment by paulkim26** [comment]
@Brushstroke90 Can you provide context for why you closed this issue? This issue is not fixed yet in the current main branch.

**Comment by mrogx** [comment]
It's fixed/done now. :D
